version: '3'

networks:
  app_network:
    driver: bridge
    driver_opts:
      com.docker.networks.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16

services:
  app:
    build: .
    volumes:
      - .:/fastapi
    ports:
      - 8000:8000
    tty: true
    networks:
      app_network:
        ipv4_address: 172.21.0.2
  db:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=passw0rd
    networks:
      app_network:
        ipv4_address: 172.21.0.3
volumes:
  db-store: